[platformio]
default_envs = native

[env:native]
platform = native
test_framework = googletest
build_flags =
    -std=c++17
    -Isrc
    -Itest

  -fsanitize=address
  -fsanitize=undefined
  -lasan
  -lubsan
	-g

test_build_src = true
